### ISSUE TITLE
Web Server: 404 File Not Found.

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#104]
When connecting to the server, it's not seeing any of the web files. This is just a reminder issue as we have already talked about this @DeathCradle.

**Comment by DeathCradle** [comment]
Does this issue occur with the latest files still?
I'd like to resolve this. Also make sure you're using my permissions.xml file from the Binaries\Data directory or at least the web section from it. In addition remove Data\web.logins from the tdsm directory so the test web logins are restored (in the case I've changed them)

**Comment by DeathCradle** [comment]
This has now been replaced with OWIN, http://<server>:8448/web should do the trick now. However instead of being directly in TDSM it will be in a separate OTA plugin located here: https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/tree/master/WebInterface
I'll close this issue off as it's separate, and not yet fully under way. When the time comes (and if there are issues) we can simple make a new one for the RAWS.
