### ISSUE TITLE
Shortly after joining the server, server exits as "Killed".

### ISSUE THREAD

**Issue by Zippynik** [DeathCradle/Terraria-s-Dedicated-Server-Mod#120]
I pressed no key combinations that may have killed the server.
Here is the pastebin: http://pastebin.com/3MSmAMsn .

**Comment by DeathCradle** [comment]
Hi Zippynik.

Would you be kind enough to give some of your machines spec's, mainly how much RAM you have available.

**Comment by Zippynik** [comment]
I have 1gb of RAM on the cheapest rootnerds.com vps

-----Original Message-----

**Comment by Zippynik** [comment]
I would also like to note that the highest ram usage I got from tdsm was 85-90%

-----Original Message-----

**Comment by D1G1T4L3CH0** [comment]
What size world? Does this happen with all three sizes?

Also the server can't use 100% of your ram since the OS needs to use some as well as other processes. So if TDSM is using that much, it may be using all of what remains of free memory and then starts using swap space. In my experience, I've recently dealt with low memory situations. I had different results than you however, but I also had more ram available.

You can try issuing the `free -m` command on the linux server, not tdsm. The output should be in megabytes. See the `+/- buffers/cache` line. See how much you have left while tdsm is running. Try to free some ram if the free ram is low then test again.

It seems like the server runs terribly and has unexpected crashes when using swap space. Good news is that @DeathCradle is working on memory optimizations, but it may not be ready until tdsm b4.

I'm not sure that's your problem however, it likely could be something else entirely.

Does it happen every time you issue the `version` command? Does it happen if you don't issue that command?

**Comment by Zippynik** [comment]
I have tried with all three sized worlds, with the latest version of the server, but all have the same error. 
free -m says I have 363MBs free under the +/- buffers/cache line and 2MB under the Memory line.

**Comment by D1G1T4L3CH0** [comment]
Hey. I'm not certain of the issue yet. I've also spoken with others about it. All we come up with is the memory limitation you have despite that 300 the system reports.

There is also [a thread on the TShock forum](https://tshock.co/xf/index.php?threads/mono-terrariaserver-exe-killed.2265/) about the same issue.

There is some good news though. @DeathCradle is working on some good memory optimizations for TDSM that should help a lot. Just keep an eye out for that update. :smile:

**Comment by DeathCradle** [comment]
Hi @Zippynik. Recently we had another fellow come in on Slack who had similar issues and increasing ram did not help all that much. So after he fiddled around with increasing the available swap things started working. Should you try and need help he suggested this link for you: http://www.cyberciti.biz/faq/linux-add-a-swap-file-howto/

**Comment by D1G1T4L3CH0** [comment]
Resolved?

**Comment by CJKay** [comment]
I'm also having this issue: http://pastebin.com/XinpwtgK
free -m log: http://pastebin.com/tRuY9aaw

**Comment by evil-dan2wik** [comment]
It looks like that for stability's sake, a swap file or partition may be needed anyway, even if it is as small as 1GB.

**Comment by DeathCradle** [comment]
I'm going ahead and closing this off now. It's been a while, and with the memory modifications in beta-b6, it's as good as it's going to get for a while.
