### ISSUE TITLE
Color Differences In Base Skin

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#184]
Other players' base skin looks dark colored to you. With accessories or armor / vanity items on, the colors do not look different.

As you can see in the below image, I'm running two clients, two different characters. I have removed all armor and accessories from both.
![different colors](https://cloud.githubusercontent.com/assets/1936606/9352480/90f2ca28-462f-11e5-84dd-ca14a7112095.png)

**Comment by DeathCradle** [comment]
You found a little treasure here :+1: 
Turns out it wasn't SSC, rather the whole API. Disabling SSC altogether led me back to the reading packet. Something was a little off, but I ended up rewriting something simpler that works. All players should now look like they are mean to, in and onward from 794c72a22f6627563b60a2cc1343779f685d9344

**Comment by D1G1T4L3CH0** [comment]
resolved
