### ISSUE TITLE
Chest Renaming Working Client Side Only

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#66]
Renaming a chest is only visible client side, and when rejoining the server, it's back to default. Another player renaming a chest cannot be seen. The server must not be actually receiving that data.

I'm also getting `Unkown send packet: 59` on the console. And no, "Unkown" is not my typo. :tongue: But I fixed it. :wink:

**Comment by DeathCradle** [comment]
Should now be fixed in: fe0e3e7d4cfddc18d74da16ab2c4b277e3c518eb
The player in range of chest code was using the x/y specified by the client (not a good idea), it should have been using the coords of the chest referenced.
Since that was incorrect, the player was never in range as the x/y sent from the client was 0.

**Comment by D1G1T4L3CH0** [comment]
Confirmed fixed.
